export const renameDispatchs = [
  { event: 'unlinkDir', path: 'home/multi/first' },
  { event: 'unlinkDir', path: 'home/multi/second' },
  { event: 'unlinkDir', path: 'home/multi/third1/third-child1' },
  { event: 'unlinkDir', path: 'home/multi/third1/third-child2' },
  { event: 'unlinkDir', path: 'home/multi/third1/third-child3' },
  { event: 'unlinkDir', path: 'home/multi/third1' },
  { event: 'unlinkDir', path: 'home/multi' },
  { event: 'unlink', path: 'home/multi/first/index.vue' },
  { event: 'unlink', path: 'home/multi/second/index.vue' },
  { event: 'unlink', path: 'home/multi/third1/third-child1/index.vue' },
  { event: 'unlink', path: 'home/multi/third1/third-child2/index.vue' },
  { event: 'addDir', path: 'home/multi3' },
  { event: 'addDir', path: 'home/multi3/first' },
  { event: 'addDir', path: 'home/multi3/second' },
  { event: 'addDir', path: 'home/multi3/third1' },
  { event: 'addDir', path: 'home/multi3/third1/third-child1' },
  { event: 'addDir', path: 'home/multi3/third1/third-child2' },
  { event: 'addDir', path: 'home/multi3/third1/third-child3' },
  { event: 'add', path: 'home/multi3/third1/third-child2/index.vue' },
  { event: 'add', path: 'home/multi3/third1/third-child1/index.vue' },
  { event: 'add', path: 'home/multi3/second/index.vue' },
  { event: 'add', path: 'home/multi3/first/index.vue' }
];
